export default ({
    "OFFERS_FETCH_LAUNCH": "OFFERS_FETCH_LAUNCH",
    "OFFERS_FETCH_SUCCESS": "OFFERS_FETCH_SUCCESS",
    "OFFERS_FETCH_ERROR": "OFFERS_FETCH_ERROR",

    "OFFER_FETCH_LAUNCH": "OFFER_FETCH_LAUNCH",
    "OFFER_FETCH_SUCCESS": "OFFER_FETCH_SUCCESS",
    "OFFER_FETCH_ERROR": "OFFER_FETCH_ERROR",
    "OFFER_UPDATE_COUNT": "OFFER_UPDATE_COUNT"
});