export default ({
    "USER_LOGIN_LAUNCH": "USER_LOGIN_LAUNCH",
    "USER_LOGIN_SUCCESS": "USER_LOGIN_SUCCESS",
    "USER_LOGIN_ERROR": "USER_LOGIN_ERROR",
    "USER_SIGNUP_LAUNCH": "USER_SIGNUP_LAUNCH",
    "USER_SIGNUP_SUCCESS": "USER_SIGNUP_SUCCESS",
    "USER_SIGNUP_ERROR": "USER_SIGNUP_ERROR",
});